CREATE TABLE IF NOT EXISTS notes (id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL, tag TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()));
CREATE TABLE IF NOT EXISTS tts_ledger (hash TEXT PRIMARY KEY, kind TEXT NOT NULL, hits INTEGER NOT NULL DEFAULT 0);
